### ISSUE TITLE
[Suggestion] Public API

### ISSUE THREAD

**Issue by levimeahan** [gidox1/TurboLogger#1]
Currently the public API is rather verbose and fragmented. Examples:

**Fragmentation**
* Currently there are two entirely separate loggers created in entirely different ways
  * `const logger = require('turbo-logger').createStream(config).log();`
  * `const logger = require('turbo-logger').createStream(config).log();`
* If you create a logger from `.createStream()`, you cannot call `.slack()` on it. You must create a separate slack-specific logger from `.slackStream()`, and the opposite is also true
* `.createStream()` requires you to also call `.log()`, `.slackStream()` does not
* Slack version uses a single method `logger.slack()` that requires an additional `context` parameter while console version instead uses different methods for each context: `logger.info()`, `logger.warn()`, `logger.error()`

The different loggers should be combined into a single object capable of logging to any destination simply by calling different methods on it, with a consistent API (either single methods like 
```javascript
console(message, context);
slack(message, context);
```

or distinct methods like 
```javascript
consoleLog(message)
consoleWarn(message)
consoleError(message)
slackLog(message)
slackWarn(message)
slackError(message)
 ```

Personally I am a fan of the distinct methods approach.

**Verbosity**
To create a basic logger, it requires: `const logger = require('turbo-logger').createStream(config).log();` - This could be simplified into
```javascript
const TurboLogger = require('turbo-logger');
const logger = new TurboLogger(config)
```
or
`const logger = require('turbo-logger').setConfig(config)` 
or 
`const logger = require('turbo-logger')(config)`
 or
`const logger = require('turbo-logger'); // Have config specified in app's package.json`

**Comment by gidox1** [comment]
Thanks Levi!

```
The different loggers should be combined into a single object capable of logging to any destination simply by calling different methods on it, with a consistent API (either single methods like
```
This made perfect sense, to promote reusability and unison. 

I would work on your suggestions and keep you in the loop.

Thanks again Buddy!

**Comment by djunehor** [comment]
I'm also of the opinion that the logger should be usable with less code.
You know for normal js, we do `console.log(); console.error; console.info()`

Turbo logger should be usable like:
```
const TurboLogger = require('turbo-logger');
const log = new TurboLogger(config);

log.info();
log.error();
log.warning();
```

I'd have dipped hands in the code, but I'm not sure of how far you've gone with the feature yet as this issue was raised some days ago.

**Comment by gidox1** [comment]
Thanks for the suggestions, @djunehor 
Will take that into consideration in the next version.

**Comment by gidox1** [comment]
Hello @djunehor  and @levimeahan 
I've updated the project with your suggestions. Thank you!

**Comment by djunehor** [comment]
Works fine now 😎

**Comment by levimeahan** [comment]
Looks better, I like this direction! The two suggestions I still have would be

1) Centralize the config (either to a file or to the app's `package.json`). Developers probably want to require the logger and use it in many different places, without having to redeclare the config in every file of the application they use it in. 
2) Make distinct methods or a parameter so that specific locations can be targeted without changing the config object. I could easily see myself wanting to log to different destinations in the same file, and having to recreate the logger with a new config object is a lot of effort to go through to do that.

**Comment by gidox1** [comment]
Thank you @Levi!
I'll get on it!

Would effect it in the next version.

**Comment by gidox1** [comment]
Hello @levimeahan 
I just published changes with the suggestions you made.

- Added env feature, so you can specify how you want to log.

Do have a look, please.

Thanks!
